import { WATER_GOALS_TABLE } from '../schemas/waterGoal';
import { WATER_LOGS_TABLE } from '../schemas/waterLog';
import {
  BODY_MEASUREMENTS_TABLE,
  FOODS_TABLE,
  MEAL_LOGS_TABLE,
  NUTRITION_GOALS_TABLE,
  WEIGHT_LOGS_TABLE,
  WORKOUT_EXERCISES_TABLE,
  WORKOUT_SETS_TABLE,
  WORKOUTS_TABLE,
} from '../schemas/slice2';
import {
  GOAL_CHECK_INS_TABLE,
  GOALS_TABLE,
  HABIT_LOGS_TABLE,
  HABITS_TABLE,
  SLEEP_LOGS_TABLE,
  SUPPLEMENT_LOGS_TABLE,
  SUPPLEMENTS_TABLE,
} from '../schemas/slice3';

/** All tables synced in the mobile offline-first app. */
export const SYNC_TABLES = [
  WATER_LOGS_TABLE,
  WATER_GOALS_TABLE,
  WORKOUTS_TABLE,
  WORKOUT_EXERCISES_TABLE,
  WORKOUT_SETS_TABLE,
  FOODS_TABLE,
  MEAL_LOGS_TABLE,
  NUTRITION_GOALS_TABLE,
  WEIGHT_LOGS_TABLE,
  BODY_MEASUREMENTS_TABLE,
  SLEEP_LOGS_TABLE,
  HABITS_TABLE,
  HABIT_LOGS_TABLE,
  SUPPLEMENTS_TABLE,
  SUPPLEMENT_LOGS_TABLE,
  GOALS_TABLE,
  GOAL_CHECK_INS_TABLE,
] as const;

export type SyncTableName = (typeof SYNC_TABLES)[number];

/** @deprecated Use SYNC_TABLES */
export const PILOT_SYNC_TABLES = SYNC_TABLES;
